### ISSUE TITLE
Make consult-bibtex a package?

### ISSUE THREAD

**Issue by stevenbagley** [mohkale/emacs#1]
I was searching for `consult-bibtex` and found your great init setup. You might consider putting that code into a package and releasing it.

**Comment by mohkale** [comment]
@stevenbagley 

Yes you're right it's suitably useful enough to justify movement into its own package. I believe there was some work on removing ivy/helm requirements from bibtex-completion and supporting a completing-read interface which is why I hadn't yet.

But I'm not sure how that's progressing so this should be done first. I'll externalise it later today and then close this issue. :smile:

**Comment by stevenbagley** [comment]
That's great. A couple of points: I don't see the need for "+" at the end of the functions and variables. Also, you might want to harmonize the bindings in embark-bibtex-completion-actions with those in bibtex-actions-map and bibtex-actions-buffer-map (both in the bibtex-actions package). Anyhow, thanks for all your work on this.

**Comment by mohkale** [comment]
@stevenbagley 

The plus suffix is purely for my dotfiles (makes distinguishing stuff I've done from what others have done much easier). When I create an external package I make sure to remove it XD.

As for your comments regarding `bibtex-actions-map`  and `bibtex-actions-buffer-map` that's probably a good idea and I'm more than happy to accept a PR for it.

Regardless everything should be ready. Please try out [mohkale/consult-bibtex](https://github.com/mohkale/consult-bibtex).

**Comment by stevenbagley** [comment]
It looks great. I did spend some time staring at the bindings in ivy-bibtex, bibtex-actions, and consult-bibtex. While there is overlap, there are also some differences that would require other packages changing their bindings. Perhaps others will have some stronger feelings or better ideas. In any case, they can change the bindings themselves.
