### ISSUE TITLE
Is this config tested on macos?

### ISSUE THREAD

**Issue by srustamo** [mohkale/emacs#2]
Tried to build the config on macos 10.14.6 with:
 ```
./bin/emacs-tangle -i -d lisp/+config.el

```

I get:
```

|Error (use-package): Failed to parse package persistent-scratch: Invalid function: plist-pop!
|Error (use-package): Failed to parse package +lib-buffer-control: Invalid function: plist-
|Error (use-package): Failed to parse package +lib-unpackaged: Invalid function: plist-
|Error (use-package): Failed to parse package hydra: Invalid function: plist-pop!

|Warning (initialization): An error occurred while loading ‘/Users/s1/.emacs’:
|Symbol's value as variable is void: leader-hydra-leader-prefix
```

**Comment by mohkale** [comment]
@srustamo 

> Is this config tested on macos?

No, since I only use linux. It should work on windows since I initially started off on there but I've never used macos. It's probably worth clarifying these aren't dotfiles I really expect anyone else to use. More often than not their probably broken since I keep a lot of new commits on my local machine before pushing. I've been meaning to setup a test-suite but I install so many packages that I didn't want to spam MELPA whenever I update my dotfiles.

> I get

Is the output you're sharing from emacs? Could you run with `--debug-init` and share the resulting stack-trace. The first few errors seem to be because of a macro that isn't defined but I'm not getting that error so I can't reproduce.

It'd probably be helpful if you zipped up your .emacs.d? Although yours seems to have tangled into ~/.emacs instead which isn't possible with my configuration.

**Comment by srustamo** [comment]
I was curious about the all-the-icons and nerd-fonts in tty related code, since I am trying to fix messed up icons in my tty emacs config in dired (all-the-icons-dired).

Tried to lift the relevant sections from init.org, into my config, no errors. However, the icons in dired mode are messed up. 

Thus cloned your config to test if the icons related code works in your config in macos.

**Comment by mohkale** [comment]
@srustamo 

> Tried to lift the relevant sections from init.org, into my config, no errors. However, the icons in dired mode are messed up.

Share a screenshot please.

**Comment by srustamo** [comment]
The screenshot is a part of the tty screen running emacs, showing dired buffer.
 
Edit: the tty is iTerm2, font used is Hack Nerd Font, patched.

<img width="708" alt="image" src="https://user-images.githubusercontent.com/749813/135112680-856f8d86-298c-4b71-a478-c2d781967514.png">

**Comment by mohkale** [comment]
@srustamo 

Looks like some glyphs are missing (the rhombus with a question mark) and others aren't beeing associated properly (the suitcase). In my terminal I've got [multiple fonts setup](https://github.com/mohkale/st/blob/1de860cfeef93e094268b90dd48e2105c25c8bcc/config.h#L8) including all the all-the-icons fonts; when emacs draws one it checks each font for a matching glyph in turn falling back to the next. I'm not sure whether iterm supports this but you should try to do so as well.

As for your other issues I don't convert every all-the-icon glyph to its equivalent nerd font. I really only do this for glyphs as I encounter them (which you can see in the config I shared before). For example `((all-the-icons-alltheicon . "c-line") . (all-the-icons-nerd-custom . "c"))` converts any references to `c-line` with alltheicon fonts to `c` with nerd-custom font. Annoyingly some parts of all the icons hardcodes references to icons into functions for example the suitcase icon being used for symlinks and the only way to fix that is with advice (but it's too big a job for me to bother).

When in doubt you can run `all-the-icons-insert` to determine which icon is being inserted where and maybe see alternatives for it.

![Screenshot_20210928_161508](https://user-images.githubusercontent.com/23294780/135115661-0ec26a3d-80e6-44da-87d6-2fcda305b935.png)

**Comment by srustamo** [comment]
Looks like I need to read up on the font rendering in tty. Any suggested resources?

iTerm2 has only this option for non-ASCII fonts:
![image](https://user-images.githubusercontent.com/749813/135251933-50cf7972-d485-402d-a322-d878d3126974.png)

Tried many fonts - blindly - not much luck. [This all-the-icons issue tracker issue](https://github.com/domtronn/all-the-icons.el/issues/141#issuecomment-475994729) says iTerm can set one non-ASCII font.
 
The `all-the-icons` [readme](https://github.com/domtronn/all-the-icons.el#troubleshooting) has a troubleshooting section. The first step, running `(all-the-icons-insert-icons-for 'alltheicon)` shows the correct icons, other commands show question marks in rhombuses.
<img width="408" alt="image" src="https://user-images.githubusercontent.com/749813/135252910-f07c10b1-819e-4bca-ab36-86d27aacbfe1.png">

`(all-the-icons-insert-icons-for 'octicon 10)`
<img width="397" alt="image" src="https://user-images.githubusercontent.com/749813/135253615-bdb994f6-b563-432e-837d-97ae6c21da71.png">


Sorry for just dumping my observations here, perhaps you can point me to the right direction.

**Comment by mohkale** [comment]
@srustamo 

Well my normal response would be to stop using iterm. Frankly this is the same reason I stopped using alacritty. Although I'm aware macos doesn't have as many alternatives and iterm2 seems to be more than just a terminal emulator, it also supports window oriented multiplexing which is quite cool. That said you might want to try kitty if you're looking for a feature-full cross platform terminal emulator.

The alternative would be to patch your own font. It might be a little involved but you can combine each of the fonts used by all-the-icons arranging the overlapping glyphs in the order you want. Not ideal but it should work. You may also want to include nerd-fonts or just use it as your main font since iterm appears to let you select a ascii and unicode font independently.

**Comment by srustamo** [comment]
Indeed, I tried alacritty, which also doesn't support fontsets.

kitty's readme says it supports multiple fonts, so far I only saw separate font definitions for Regular, Italic etc, and font maps for specific ASCII codes, which seems something I need to explore more.

Many thanks for your tips.

**Comment by srustamo** [comment]
You don't use Evil mode in emacs tty, do you? If you do, how do you manage Ctrl-I (vim's jump forward) and TAB, which is normally not differentiated from Ctrl-I in ttys?

**Comment by mohkale** [comment]
@srustamo 

I do use evil in the terminal. See [here](https://github.com/mohkale/emacs/blob/master/init.org#term). I ended up just remapping some of the terminal specific bindings into custom keys (eg: `[C-i]`) which I bind separate to `"TAB"`/`"C-i"` (which emacs internally stores as a literal tab character `\t`). For something a little less manual you may want to try [term-keys](https://github.com/CyberShadow/term-keys).
